### ISSUE TITLE
missing test property on compiled files

### ISSUE THREAD

**Issue by GiladShoham** [teambit/envs#10]
When using both compiler and tester in bit, bit will send to the tester the compiled files.
In order for bit to know which compiled files consider test files the compiler should add dist=true prop on the returned vinyl files.
The current version of the typescript (3.0.35), react-typescript(3.0.27) and angular (0.2.0) compilers are missing this prop so the tester getting empty test files array.

**Comment by Mouvedia** [comment]
Is [bit.envs/compilers/stencil](https://bit.dev/bit/envs/compilers/stencil) also affected?

**Comment by GiladShoham** [comment]
@Mouvedia By looking at the code, it might have the same bug.
I would recommend open a new issue for this.
@JoshK2 can you please verify it?

**Comment by JoshK2** [comment]
I fixed this in the Stencil compiler and all the compiler that use the readFiles function from here:
https://bit.dev/bit/envs/compilers/utils/~code#files.utils.ts
