### ISSUE TITLE
.txt file support in ts compiler

### ISSUE THREAD

**Issue by KutnerUri** [teambit/envs#103]
It'd be nice to have `.txt` file support.
```tsx
import content from './final-texts.txt';

//content is string
```
For example, I'm writing a test with a text snapshot. Currently I'm using `export default '...'`, but it'd be nice to replace it with a whole txt file.

**Comment by KutnerUri** [comment]
I just realised this will require some support from the consuming environment, like a webpack plugin, and will damage the component isolation.

Worse case, adding a `.d.ts` file to the component can make ts compiler support it:
```ts
//(at final-texts.d.ts)
declare const content: string;
export default content;
```

**Comment by qballer** [comment]
Closed for not being clear
