### ISSUE TITLE
Angular Compiler requires TypeScript >=3.6.4 and <3.9.0 but 3.9.2 was found instead

### ISSUE THREAD

**Issue by brusand** [teambit/envs#139]
### Describe the bug

A clear and concise description of the issue.

### Steps to Reproduce

1. update to node 10.2.18
2. bit build
3.

### Screenshots, exceptions and logs
error: bit failed to build product-list@0.0.1 with the following exception:`
error: bit failed to build product-list@0.0.1 with the following exception:
The Angular Compiler requires TypeScript >=3.6.4 and <3.9.0 but 3.9.2 was found instead.
Error: The Angular Compiler requires TypeScript >=3.6.4 and <3.9.0 but 3.9.2 was found instead.
 
If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version:
- Node version:
- npm / yarn version:
- Platform:
- Compiler / Tester (include version):

### Additional context

 vi .git/bit/components/compilers/angular/bit.envs/9.0.14/node_modules/@angular/compiler-cli/src/typescript_support.js
    var MAX_TS_VERSION = '3.9.5'; and it is ok

**Comment by danielhdz56** [comment]
running into the same issue. 
when i run ng version the typescript version falls within the range >=3.6.4 and <3.9.0
when i check the package.json it is the same as running ng version.

Ive deleted node_modules, package_lock, and cleared the npm cache and still running into this problem.

**Comment by itaymendel** [comment]
@JoshK2 @qballer what do you think?
is it possible to commit @brusand 's workaround to the compiler to resolve it?

**Comment by Deekor** [comment]
Been struggling with this all night. Glad I'm not the only one with the problem. I thought I was going crazy.

**Comment by danielhdz56** [comment]
@Deekor same. I didn't notice that they had this workaround:

vi .git/bit/components/compilers/angular/bit.envs/9.0.14/node_modules/@angular/compiler-cli/src/typescript_support.js
var MAX_TS_VERSION = '3.9.5';

**Comment by GiladShoham** [comment]
@JoshK2 Please take a look?

**Comment by JoshK2** [comment]
Hi @brusand @danielhdz56 @Deekor 

I solved this issue and release a new version of the Angular compiler, version 9.0.17.
https://bit.dev/bit/envs/compilers/angular?version=9.0.17
