### ISSUE TITLE
 Property 'accordionHeaderTemplate' has no initializer 

### ISSUE THREAD

**Issue by brusand** [teambit/envs#148]
### Describe the bug
lines like :
    @ContentChild(TemplateRef) accordionHeaderTemplate: TemplateRef<any> ;

bit build, generate the error Property 'accordionHeaderTemplate' has no initializer 
normal  TemplateRef<any> is an abstract class , and by default angular compiler setting in tscconfig is 
  "angularCompilerOptions": {
    "strictInjectionParameters": true
  },
### Steps to Reproduce

1.
2.
3.

### Screenshots, exceptions and logs

If applicable, add screenshots, exceptions, and logs to help explain your problem.

### Specifications

- Bit version: last
- Node version: 10
- npm / yarn version: npm
- Platform: mac
- Compiler / Tester (include version): angular 9

### Additional context
how to override this option in env/compiler like 
  "bit": {
    "env": {
      "compiler": "bit.envs/compilers/angular@9.0.17",
      "rawConfig": {
        "tsconfig": {
          "angularCompilerOptions": {
            "strictInjectionParameters": false
          }
        }
      }
    },

**Comment by GiladShoham** [comment]
you might want to try with angular 8 instead of 9

**Comment by brusand** [comment]
I use  //ts ignore it id ok

Le lun. 22 juin 2020 à 13:25, Gilad Shoham <notifications@github.com> a
écrit :

**Comment by JoshK2** [comment]
Hi, a new version of the Angular compiler was published, please try it.
https://bit.dev/bit/envs/compilers/angular?version=9.0.22
