### ISSUE TITLE
[BUG] Angular env - component with @Input

### ISSUE THREAD

**Issue by lifaon74** [teambit/envs#153]
### Describe the bug

I have exported a component, on bit dev, based on Angular 9, which includes an `@Input` (which is extremely common for Angular). The components builds and works properly locally, but doesn't load correctly on `https://bit.dev/[org name]/[collection]/[name]`

### Steps to Reproduce

```ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'my-component',
  template: '{{ content }}',
  styles: []
})
export class MyComponent {
  @Input() content = '';

  constructor() {
  }
}
```

app.component.html:

```
<my-component [content]="'hello world'"></my-component>
```

On the playground it generates:

```
Uncaught Error: Template parse errors:
Can't bind to 'content' since it isn't a known property of 'my-component'.
```

Of course, it includes a `.module.ts`

Usually this bug comes from incorrect import/export of metadata (Angular's decorator metadata)

### Specifications

- Bit version: 14.8.8
- Node version: 12.18.3
- Platform: linux
- Compiler / Tester (include version): bit.envs/compilers/angular@9.0.21

### Aditional

It may be useful to express a little more functionalities of Angular on the _bit-angular-tutorial:_ https://github.com/teambit/bit-angular-tutorial/blob/master/src/app/product-list/product-list.component.ts like: `@Input, @Output, @Directive, @Service`, if you're running tests on it

**Comment by JoshK2** [comment]
Hi, I close this issue, I merged and exported a new version with your fixes:
https://github.com/teambit/envs/pull/154
Thanks for your fixes.
