### ISSUE TITLE
React 17 and Typescript 4 support in react-typescript env

### ISSUE THREAD

**Issue by lironhl** [teambit/envs#166]
### Description

React 17 is out, and I'd like a support for it from **react-typescript** env.
[It seems like the peer dependencies are React 16](https://github.com/teambit/envs/blob/master/packages/react-typescript/src/react-preset.ts) and the [TSConfig also lacks support for React 17](https://github.com/teambit/envs/blob/master/packages/react-typescript/src/tsconfig.ts) (for example the `jsx` value equals `react` and not `react-jsx`.

### Describe the solution you'd like

I'd like both of those things updated, I'd gladly do it myself, but the docs lack a documentation about how to build/run/test the env.

### Describe alternatives you've considered

I'm able to change the TSConfig properties but not the `peer dependencies`.

### Additional context

None

**Comment by JoshK2** [comment]
Hi @lironhl thanks for opening the issue.
I published a new version of the react-typescript compiler that now supports React 17.
https://bit.dev/bit/envs/compilers/react-typescript?version=3.1.65
