### ISSUE TITLE
SVG doesn't get compile correctly

### ISSUE THREAD

**Issue by jackguoAtJogg** [teambit/envs#18]
Currently, when I import svg inside my component, it won't compile correctly when I added as a bit component. I believe it's treating the svg as components.

![image](https://user-images.githubusercontent.com/56273621/68881207-8bac4880-06c1-11ea-98c9-0950609fa9c0.png)

------
Bit version: 14.4.3
Node version: 10.16.3

**Comment by qballer** [comment]
Hi @jackguoAtJogg thanks for opening an issue. The new version of the compiler should solve this issue please run.
```
bit import bit.envs/compilers/react-typescript -c
```

**Comment by seed-of-apricot** [comment]
@qballer I have the same issue with **typescript** compiler (ver. 3.1.40).
I have a custom @types definition under `src/@types` folder and `tsc` works correctly.

Realted issue: teambit/bit.envs#58
