### ISSUE TITLE
replace promises as fs by fs-extra in ts compiler

### ISSUE THREAD

**Issue by GiladShoham** [teambit/envs#24]
The promises fs feature is pretty new in node and marked as experimental. 
This yield an annoying warning every time someone using the ts-compiler - 
`(node:7885) ExperimentalWarning: The fs.promises API is experimental`
Behind it's annoying, it means that:
1. It won't work for users with a bit older node version
2. it might be break in the future since the node team is not committed to the API.

I suggest replacing it by fs-extra, it has exactly the same API and will solve all the issues.
The only downside is another dependency.
But since a compiler is rarely installed, and it doesn't affect the production bundle, it looks very minor issue to me.

**Comment by qballer** [comment]
A compiler shouldn't be using either of them, but a promise based API provided by Capsule. Future development might mean different kinds of component containers. This means that the extensions need to be agnostic to the isolated environment. This is a missing feature in bit at the moment.

**Comment by davidfirst** [comment]
@qballer , Until this is done, I'd suggest switching to fs-extra as Gilad mentioned.
It's also annoying to get a cryptic error about fs.writefile not found (or something similar) when running node 8. 
Switching to fs-extra will fix this as well.

**Comment by qballer** [comment]
Cool. Will get on it.
