### ISSUE TITLE
CONTRIBUTING.md file

### ISSUE THREAD

**Issue by imsnif** [teambit/envs#39]
It would be great if we could have a basic CONTRIBUTING.md file that tells us how to use this repo.

It should include all the steps from cloning the repo up to using a built compiler/tester in a different project with bit.

**Comment by qballer** [comment]
Can you provide specific bullets on what you would like to see there. 
- options/file explained? 
- build /test cycle ? 
- project structure?

**Comment by imsnif** [comment]
* how to build a compiler/tester
* how to use it in your project

The best would be simple 2-3 steps of copy-pastable instructions. No explanations necessary - just something that would work and we wouldn't have to think about.
