### ISSUE TITLE
typescript compiler should transpile import statements

### ISSUE THREAD

**Issue by KutnerBitsrc** [teambit/envs#44]
I just updated to typescript compiler version 3.1.12.
I wanted to tag the component, but to my surprise my tests fail:
```
✖ Cannot use import statement outside a module 
```

Looking at the /dist/ files, I see output files still have import and export statement.
This means that typescript components cannot be used in node environment, like:
* web project's serverside rendering
* bit.envs/testers/mocha
* all node applications 

Since I have tests on my component, I cannot tag it without transpiling the source code.
Even if I didn't have tests, I would never dare to release it with experimental features.

I found this hack to override the compiler defaults:
```
// at package.json
"bit.envs/compilers/typescript@3.1.12": {
  "rawConfig": {
    "tsconfig": {
      "compilerOptions": {
        "target": "ES5",
        "module": "CommonJS"
      }
    }
  }
}
```

please make ES5/CJS the default configuration, as it is most supported and the de facto standard at the moment.

### reference:
  bit version   : 14.5.0
  node version  : v12.12.0
  npm version   : 6.11.3
  yarn version  : 1.19.1

**Comment by qballer** [comment]
When starting to rebuild the environments we had a choice are we future proof by default or not. For the sake of users targeting the browser, a decision was made to use ES6.  You may read more in project readme. I did leave room for the user to make their own choices by overriding the configuration. This still has it's faults and will be improved as we go. You have several options to go about this. 

- Target ES5 by configuring the compiler (like you pointed out). 
- Use node 12 or turn on es6 flag on older version. 
- Use https://github.com/standard-things/esm 
- roll your own environment

The mocha tester will be getting a major update, and this issue will be addressed.  Thanks for pointing it
