### ISSUE TITLE
React Native Typescript Compiler?

### ISSUE THREAD

**Issue by Oba-One** [teambit/envs#57]
Hi! I'm looking to mesh both the react-typescript and react-native compilers. Does anyone have a working example or can point me in the direction to build one.

**Comment by qballer** [comment]
hi @Oba-One, what do you mean by meshing these compilers together!? Are you trying to implement react-native component with typescript? Do you have a project where you have both react-native and react-dom components. More details will be appreciated.

**Comment by kaduelinho** [comment]
@qballer i'm creating a reat-native component with typescript. What i should do in this case?

**Comment by qballer** [comment]
@JoshK2 has been working on this problem and should be able to provide more information about it. If I have the right picture, he should release an environment soon which handles react-native-typescript We will update here.

**Comment by Oba-One** [comment]
Hi, Just saw this @qballer  I have a react native project in typescript and want to compile it to view in bit. I haven't tried since then but will attempt to make my own/see what @JoshK2  creates.

**Comment by JoshK2** [comment]
Hey @Oba-One  
A few days ago I release the [RN compiler](https://bit.dev/bit/envs/compilers/react-native) but it currently not support RN with TS.
I work now for supporting TS.

**Comment by Oba-One** [comment]
Thanks! @JoshK2

**Comment by developerantoniosousa** [comment]
@JoshK2 I look forward to the react native compiler with typescript. Is there a release date?

**Comment by JoshK2** [comment]
@developerantoniosousa 
@Oba-One 
The react native is an experimental compiler. We are currently holding its maintenance die to other priorities. You are welcome to send a PR.

**Comment by olgaababic** [comment]
Hey @JoshK2 is there any news regarding react-native compiler with typescript support?

**Comment by rafaelsaback** [comment]
Looking forward to having the TypeScript support added to the RN compiler. Btw, great job you're doing with bit! :rocket:

**Comment by JoshK2** [comment]
Hi, I think a possible workaround would be to add this babel preset:
https://babeljs.io/docs/en/babel-preset-typescript
to the `.babelrc` file of the compiler:
https://github.com/teambit/envs/blob/master/packages/react-native/.babelrc

It will not check the types like TypeScript, but it will compile all the `.ts` files.

**Comment by Oba-One** [comment]
@JoshK2 I'm trying it out now, I'll let you know how it goes

**Comment by brandonvilla21** [comment]
> Hi, I think a possible workaround would be to add this babel preset:
> https://babeljs.io/docs/en/babel-preset-typescript
> to the `.babelrc` file of the compiler:
> https://github.com/teambit/envs/blob/master/packages/react-native/.babelrc
> 
> It will not check the types like TypeScript, but it will compile all the `.ts` files.

@JoshK2 What should be the best approach for that?
Do I edit the react native compiler? something like:
```json
  "bit": {
    "env": {
      "compiler": "bit.envs/compilers/react-native@1.0.21",
      "rawConfig": {
        ".babelrc": {
          "presets": [
            "module:metro-react-native-babel-preset",
            "@babel/preset-typescript"
          ]
        }
      }
    },
    ...
  }
``` 

Or can I create a new compiler based on react-native?

**Comment by JoshK2** [comment]
Hi @brandonvilla21 
My possible workaround was to create a new compiler with the right config, but I tried it and I was not able to make it work with the current Bit version.
I want to update you and everyone in this thread, that we gonna release the biggest major version of Bit in the comings weeks, and it will help us to solve this kind of issue with TS.

**Comment by JoshK2** [comment]
@Oba-One @carloslibardo @developerantoniosousa @olgaababic @rafaelsaback @brandonvilla21 

Hi all, I published a new compiler for React native with TypeScript support! 🥳
