### ISSUE TITLE
[react-native] platform specific code

### ISSUE THREAD

**Issue by oxyii** [teambit/envs#69]
I'm new in `bit`. I have no luck to find solution in docs. Please help to configure `bit` resolver for platform-specific code like noted in [this comment](https://github.com/teambit/bit/issues/927#issuecomment-384695690)
I had a error:
```
 non-existing dependency files (please make sure all files exists on your workspace): 
          Component/index.js -> ./Component
```
My component folder structure:
```
index.js // <- export { default } from './Component'
Component.android.js
Component.ios.js
```
Both variants (android + ios) must be included into build

**Comment by GiladShoham** [comment]
Hi,
this will be handled under - https://github.com/teambit/bit/issues/2215

**Comment by oxyii** [comment]
@GiladShoham Thanks for your reply but this is not a solution exactly... it's actually easier than it sounds... The only thing I need is to explicitly list the supported file extensions. Something like [`resolveModules`](https://docs.bit.dev/docs/conf-bit-json#resolvemodules) but for file extensions. Something like [Webpack extensions resolver](https://webpack.js.org/configuration/resolve/#resolveextensions). But it must include into build all found files instead of first matched

**Comment by oxyii** [comment]
Ok, sorry for dup. Let's continue in https://github.com/teambit/bit/issues/2215
