### ISSUE TITLE
Cannot find module *.png on bit tag of typescript 

### ISSUE THREAD

**Issue by rap0so** [teambit/envs#72]
### Describe the bug

I'm trying to tag a component by running `bit tag` but the command cannot find the current compiler, it returns the error: `Cannot find module [image path]`
The url [doc](https://docs.bit.dev/docs/best-practices.html#images) with example is broken, so...

### Steps to Reproduce

1. Add an image to folder component
2. Import this image on a ts file
3. Bit tag the component

### Expected Behavior

Tagged component with imported images

### Screenshots, exceptions and logs

![image](https://user-images.githubusercontent.com/18194524/71595199-6f515780-2b19-11ea-828f-44d8e82bc522.png)

![image](https://user-images.githubusercontent.com/18194524/71595180-61033b80-2b19-11ea-9903-35d3b3de625e.png)

![image](https://user-images.githubusercontent.com/18194524/71595208-7aa48300-2b19-11ea-8bee-ccb95450bcc8.png)

### Specifications

- Bit version: 14.7.1
- Node version: v10.16.3
- npm / yarn version: 1.19.1
- Platform: Windows 10 Pro
- Compiler / Tester (include version): bit.envs/compilers/typescript@3.1.28

**Comment by qballer** [comment]
can you please share your bitmap file and bit.json file (or bit entry in package.json).

**Comment by rap0so** [comment]
**bit.json**

```
{
    "env": {
        "compiler": "bit.envs/compilers/typescript@3.1.28",
        "tester": "bit.envs/testers/jest@22.4.3"
    },
    "componentsDefaultDirectory": "src/components/{name}",
    "packageManager": "yarn"
}
```

**.bitmap**

```
/* THIS IS A BIT-AUTO-GENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY. */

{
    "empty-state@0.0.1": {
        "files": [
            {
                "relativePath": "src/components/EmptyState/EmptyState.tsx",
                "test": false,
                "name": "EmptyState.tsx"
            },
            {
                "relativePath": "src/components/EmptyState/assets/images/404.png",
                "test": false,
                "name": "404.png"
            },
            {
                "relativePath": "src/components/EmptyState/assets/images/505.png",
                "test": false,
                "name": "505.png"
            },
            {
                "relativePath": "src/components/EmptyState/assets/images/default.png",
                "test": false,
                "name": "default.png"
            },
            {
                "relativePath": "src/components/EmptyState/imageMapper.tsx",
                "test": false,
                "name": "imageMapper.tsx"
            },
            {
                "relativePath": "src/components/EmptyState/index.d.ts",
                "test": false,
                "name": "index.d.ts"
            },
            {
                "relativePath": "src/components/EmptyState/index.ts",
                "test": false,
                "name": "index.ts"
            },
            {
                "relativePath": "src/components/EmptyState/tsconfig.json",
                "test": false,
                "name": "tsconfig.json"
            },
            {
                "relativePath": "src/components/EmptyState/types.ts",
                "test": false,
                "name": "types.ts"
            },
            {
                "relativePath": "src/components/EmptyState/typings/index.d.ts",
                "test": false,
                "name": "index.d.ts"
            }
        ],
        "mainFile": "src/components/EmptyState/index.ts",
        "trackDir": "src/components/EmptyState",
        "origin": "AUTHORED",
        "exported": false
    },
    "version": "14.7.1"
}
```

**Comment by JoshK2** [comment]
Hey @rap0so,
I found the source of the problem and I work on this.
The problem is with the [`generateTypes`](https://github.com/teambit/envs/blob/master/packages/react-typescript/src/generate-types.ts) function, the output of the file is not wrapped with `declare module`, for example, the output for JPG file is:
```
const image: string;
export default image;
```
and it needs to be:
```
declare module "*.jpg" {
    const image: string;
    export default image;
}
```

Also, the file name generated is incorrect, let's say we have an image called `profile.jpg`, the file name we get is `profile.jpg.d.ts` and double extension is incorrect for this file, and it needs to be `profile-jpg.d.ts`.
We need also to not duplicate the same module file if the user have for example two png file in the same component.
@qballer

**Comment by JoshK2** [comment]
@rap0so 
I published a new version of the compiler that solved the problem:
https://bit.dev/bit/envs/compilers/react-typescript?version=3.1.31
