### ISSUE TITLE
Typescript compiler is considering the original path and not the isolated path of the component.

### ISSUE THREAD

**Issue by DeyLak** [teambit/envs#8]
### Describe the bug

`bit build` command for css modules duplicated folders structure of the original component path from project source.

### Steps to Reproduce

1. Create new CRA project
1. Add `components/test/index.tsx` and `components/test/index.module.ts` files
1. `bit add components/* --namespace components`
1. `bit tag --all`
1. `bit export your.collection`
1. `bit eject components/test`
1. `bit import your.collection/components/test`

`index.module.css` is stored inside `components/test/components/test`

### Expected Behavior
`index.module.css` should be stored in`components/test/`

### Screenshots, exceptions and logs
![image](https://user-images.githubusercontent.com/1286563/64785209-85400a00-d574-11e9-9f15-af97629a69d3.png)

### Specifications

- Bit version: 14.3.0
- Node version: v10.16.0
- npm / yarn version: 6.11.2
- Platform: MacOS 10.14.6
- Bit compiler (include version):  `bit.envs/compilers/typescript@3.0.28`
- Bit tester (include version): -

**Comment by qballer** [comment]
Can you try this:
`bit.envs/compilers/react-typescript@3.0.25` or `bit.envs.compilers.typescript@3.0.29`

**Comment by DeyLak** [comment]
thank you, `bit.envs.compilers.typescript@3.0.29` is working correctly
