### ISSUE TITLE
The React Native compiler should support JSX files

### ISSUE THREAD

**Issue by jmporchet** [teambit/envs#98]
As per our discussion on the Slack channel with @JoshK2, at the moment the react native compiler only supports `*.js` file extensions, not `*.jsx`.

It would be great to have support for these file extensions natively.

The correct Babel configuration needs to be added to make this feature.

**Comment by JoshK2** [comment]
Hi @jmporchet,

I think it would be great to support `jsx` files, if you can share the right Babel config, it would be nice.
You can also create a PR  with the new Babel config for this compiler to support `jsx`.

**Comment by jmporchet** [comment]
I wouldn't know where to start looking...

**Comment by JoshK2** [comment]
@jmporchet 
I saw how to support `jsx` in react-native, and it's only a little config in the metro config file, so no change needs to be done in the babel config file generated by the compiler.
So, I added the support for `jsx` file in the compiler, you can test it from version 1.0.15.
https://bit.dev/bit/envs/compilers/react-native?version=1.0.15
